AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple CRUD webservice. State is stored in a SimpleTable (DynamoDB) resource.
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.sample.aws.samlocal.BookGetHandler
      Runtime: java8
      CodeUri: s3://<bucket>/api_backend.zip
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /books/{bookId}
            Method: get

  PutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.sample.aws.samlocal.BookGetHandler
      Runtime: java8
      CodeUri: s3://<bucket>/api_backend.zip
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: /books
            Method: put

  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.sample.aws.samlocal.BookDeleteHandler
      Runtime: java8
      CodeUri: s3://<bucket>/api_backend.zip
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        DeleteResource:
          Type: Api
          Properties:
            Path: /books/{bookId}
            Method: delete

  Table:
    Type: AWS::Serverless::BookTable

  BookTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
        -
          AttributeName: "name"
          AttributeType: "S"
        -
          AttributeName: "isbn"
          AttributeType: "S"
        -
          AttributeName: "cost"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
