AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple CRUD webservice. State is stored in a SimpleTable (DynamoDB) resource.
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.sample.aws.samlocal.BookGetHandler
      Runtime: java8
      CodeUri: ./target/sam-local-java-1.0-SNAPSHOT.jar
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /books
            Method: get

  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.sample.aws.samlocal.BookPostHandler
      Runtime: java8
#      CodeUri: s3://aws-sam-local/books.zip
      CodeUri: ./target/sam-local-java-1.0-SNAPSHOT.jar
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: /books
            Method: post

#  DeleteFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      Handler: org.sample.aws.samlocal.BookDeleteHandler
#      Runtime: java8
#      CodeUri: ./target/sam-local-java-1.0-SNAPSHOT.jar
#      Policies: AmazonDynamoDBFullAccess
#      Environment:
#        Variables:
#          TABLE_NAME: !Ref Table
#      Events:
#        DeleteResource:
#          Type: Api
#          Properties:
#            Path: /books/{bookId}
#            Method: delete

  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
